{
 "title": "Service",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "pace_postgres_query_total" },
   { "name": "name", "query": "pace_postgres_query_total" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP",
   "type": "singlestat",
   "description": "Number of HTTP requests within the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(pace_http_request_total{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "singlestat",
   "description": "Number of HTTP requests per second, averaged over the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(pace_http_request_total{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Process",
   "type": "singlestat",
   "description": "Total RAM usage, averaged over the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(process_virtual_memory_bytes{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"})"
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "singlestat",
   "description": "Time in which 95% of all Postgres queries are processed, averaged over the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(pace_postgres_query_duration_seconds_bucket{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "singlestat",
   "description": "Number of HTTP requests that return 4xx and 5xx errors within the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(pace_http_request_total{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\",code=~\"^[45][0-9]{2}$\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "singlestat",
   "description": "Percentage of HTTP requests that return 4xx and 5xx errors, averaged over the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(pace_http_request_total{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\",code=~\"^[45][0-9]{2}$\"}[$__interval])) / sum(rate(pace_http_request_total{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Process",
   "type": "singlestat",
   "description": "Total RAM usage, averaged over the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(go_goroutines{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"})"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "singlestat",
   "description": "Time in which 95% of all Redis queries are processed, averaged over the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(pace_redis_cmd_duration_seconds_bucket{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "singlestat",
   "description": "Time in which 95% of all HTTP requests are served, averaged over the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(pace_http_request_duration_milliseconds_bucket{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "Panics",
   "type": "singlestat",
   "description": "Number of panics within the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(pace_http_panic_total{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Process",
   "type": "singlestat",
   "description": "Total RAM usage, averaged over the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(process_open_fds{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"})"
    }
   ]
  },
  {
   "title": "Livetests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pace_livetest_total{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"})"
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_api_http_request_total{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Response Times",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum(increase(pace_api_http_request_duration_seconds_bucket{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Sizes",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "sum(increase(pace_api_http_size_bytes_bucket{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_http_request_total{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Response Times",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "repeat": "database",
     "targets": [
      {
       "expr": "sum(increase(pace_http_request_duration_milliseconds_bucket{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Running Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pace_http_in_flight_requests{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"} - 1) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Response Sizes",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "sum(increase(pace_http_response_size_bytes_bucket{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "4xx Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_http_request_total{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\",code=~\"^4[0-9]{2}$\"}[$__interval])) by (code, name)",
       "legendFormat": "{{code}} ({{name}})"
      }
     ]
    },
    {
     "title": "5xx Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_http_request_total{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\",code=~\"^5[0-9]{2}$\"}[$__interval])) by (code, name)",
       "legendFormat": "{{code}} ({{name}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(process_virtual_memory_bytes{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(go_goroutines{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Panics",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_http_panic_total{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(go_threads{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Go Versions",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "max(go_info{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}) by (name, version)"
      }
     ]
    },
    {
     "title": "Open Files",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_open_fds{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Postgres Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Postgres Queries",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_postgres_query_total{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Postgres Query Times",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "sum(increase(pace_postgres_query_duration_seconds_bucket{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Postgres Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_postgres_query_failed{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (database, name)",
       "legendFormat": "{{database}} ({{name}})"
      }
     ]
    },
    {
     "title": "Rows Returned",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 106 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_postgres_query_rows_total{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (database, name)",
       "legendFormat": "{{database}} ({{name}})"
      }
     ]
    },
    {
     "title": "Rows Affected",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 106 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_postgres_query_affected_total{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (database, name)",
       "legendFormat": "{{database}} ({{name}})"
      }
     ]
    },
    {
     "title": "Connection Pool Hits",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 112 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_postgres_connection_pool_hits{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (pool, name)",
       "legendFormat": "{{pool}} ({{name}})"
      }
     ]
    },
    {
     "title": "Connection Pool Misses",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 112 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_postgres_connection_pool_misses{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (pool, name)",
       "legendFormat": "{{pool}} ({{name}})"
      }
     ]
    },
    {
     "title": "Connection Pool Timeouts",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 112 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_postgres_connection_pool_timeouts{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (pool, name)",
       "legendFormat": "{{pool}} ({{name}})"
      }
     ]
    },
    {
     "title": "Connection Pool Total Connections",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 116 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pace_postgres_connection_pool_total_conns{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}) by (pool, name)",
       "legendFormat": "{{pool}} ({{name}})"
      }
     ]
    },
    {
     "title": "Connection Pool Idle Connections",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 116 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pace_postgres_connection_pool_idle_conns{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}) by (pool, name)",
       "legendFormat": "{{pool}} ({{name}})"
      }
     ]
    },
    {
     "title": "Connection Pool Stale Connections",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 116 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pace_postgres_connection_pool_stale_conns{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}) by (pool, name)",
       "legendFormat": "{{pool}} ({{name}})"
      }
     ]
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Redis Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pace_redis_cmd_total{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Redis Times",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(pace_redis_cmd_duration_seconds_bucket{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Redis Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pace_redis_cmd_failed{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Livetests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Livetests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pace_livetest_total{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(increase(pace_livetest_duration_seconds_bucket{kubernetes_namespace=~\"^$namespace$\",name=~\"^$name$\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}